version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sinalvortex_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sinalvortex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sinalvortex_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: sinalvortex_adminer
    ports:
      - "8081:8080" # Mudei para 8081 para não dar conflito se a API rodar na 8080 localmente
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local