# Estágio de Build (.NET 10 SDK)
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build-env
WORKDIR /app

# Copia todo o código do backend
COPY backend/ ./

# Restaura as dependências do Worker
RUN dotnet restore SinalVortex.Worker/SinalVortex.Worker.csproj

# Compila e publica apenas o WORKER
RUN dotnet publish SinalVortex.Worker/SinalVortex.Worker.csproj -c Release -o out --no-restore

# Estágio de Execução (.NET 10 Runtime)
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "SinalVortex.Worker.dll"]