name: Continuous Integration (CI)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./backend

      - name: Build solution
        run: dotnet build --no-restore --configuration Release
        working-directory: ./backend

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
        working-directory: ./backend